server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #配置Nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080
        #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
service-url:
  nacos-user-service: http://nacos-payment-provider
#对Feign的支持
feign:
  sentinel:
    enabled: true