server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #开启动态路由
      discovery:
        locator:
          enabled: true
      routes:
        #路由的ID 没有固定规则但要求唯一，建议配合服务名
        - id: payment_route
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          #断言，路径想匹配的进行路由
          predicates:
            - Path=/payment/get/**
            - After=2021-10-09T11:10:03.404+08:00[Asia/Shanghai]

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            #路径
            - Path=/payment/lb/**
            #时间
            - After=2021-10-09T11:11:03.404+08:00[Asia/Shanghai]
            - Before=2033-01-20T17:42:47.789-07:00[Asia/Shanghai]
            - Between=2017-01-20T17:42:47.789-07:00[Asia/Shanghai], 2033-01-21T17:42:47.789-07:00[Asia/Shanghai]
            #cookie
            - Cookie=username,hike97
            #请求头
            - Header=X-Request-Id, \d+
            - Host=**.atguigu.com
            - Query=username, \d+ #要有参数名称并且是正整数才能路由
            - Method=GET
#        curl http://localhost:9527/payment/lb?username=1 --cookie "username=hike97" -H "X-Request-Id:123" -H "Host: www.atguigu.com"
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版